# Generated by Django 5.2.7 on 2025-11-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True, verbose_name='host_name')),
                ('ip', models.GenericIPAddressField(verbose_name='IP_address')),
                ('disk', models.CharField(blank=True, max_length=55, null=True)),
                ('mem', models.CharField(blank=True, max_length=55, null=True)),
                ('cpu', models.CharField(blank=True, max_length=55, null=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'device',
                'verbose_name_plural': 'device_List',
                'db_table': 'Host',
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='Reactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='反应釜名称')),
                ('volume_m3', models.FloatField(verbose_name='容积 (m³)')),
                ('material', models.CharField(default='不锈钢316L', max_length=50, verbose_name='材质')),
                ('pressure_bar', models.FloatField(blank=True, null=True, verbose_name='设计压力 (bar)')),
                ('temperature_c', models.IntegerField(blank=True, null=True, verbose_name='设计温度 (°C)')),
                ('install_date', models.DateField(auto_now_add=True, verbose_name='安装日期')),
            ],
            options={
                'verbose_name': '反应釜',
                'verbose_name_plural': '反应釜列表',
            },
        ),
        migrations.CreateModel(
            name='Reactor3333',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='反应釜名称')),
                ('volume_m3', models.FloatField(verbose_name='容积 (m³)')),
                ('material', models.CharField(default='不锈钢316L', max_length=50, verbose_name='材质')),
                ('pressure_bar', models.FloatField(blank=True, null=True, verbose_name='设计压力 (bar)')),
                ('temperature_c', models.IntegerField(blank=True, null=True, verbose_name='设计温度 (°C)')),
                ('install_date', models.DateField(auto_now_add=True, verbose_name='安装日期')),
            ],
            options={
                'verbose_name': '反应釜',
                'verbose_name_plural': '反应釜333列表',
                'db_table': 'Reactor3333',
            },
        ),
    ]
